### ISSUE TITLE
Add Multiple Devices in Embedded MTConnect Agent

### ISSUE THREAD

**Issue by smtpl-iiotian** [TrakHound/MTConnect.NET#61]
@PatrickRitchie this is another great development of embedded mtconnect agent. I tested it for 1 machine and it worked as expected. I was able to route Mitsubishi CNC data to MTConnect agent. But I was only able to add 1 device in the protected override IDevice OnAddDevice() function. 

Please guide how can I add x number of devices.

**Comment by PatrickRitchie** [comment]
Glad to hear you have found the embedded agent helpful. I intended for additional devices to be added by adding multiple configurations to the configuration file similar to below:

```yaml
- haas-ethernet:
    deviceKey: VF2-01
    server: 192.168.1.101
    port: 5051

- haas-ethernet:
    deviceKey: VF2-02
    server: 192.168.1.102
    port: 5051

- haas-ethernet:
    deviceKey: VF2-03
    server: 192.168.1.103
    port: 5051
```

This will create an instance of the same module for each configuration.

Let me know if this works for you or if you have any other questions or recommendations.

**Comment by smtpl-iiotian** [comment]
@PatrickRitchie very much thanks. I was able to add x number of devices after configuration update.

**Comment by smtpl-iiotian** [comment]
@PatrickRitchie is there any provision in the embedded mtconnect agent to make the executable .exe as a windows service OR I have to do it manually?

**Comment by smtpl-iiotian** [comment]
@PatrickRitchie, I tried to install published .exe as a windows service as per the above link and guide. 
I added serviceName in configuration file to add multiple windows services one for Mitsubishi and another for Modbus devices but it only gets applied as a Display name as seen in the Windows Process(image attached). 
![MTCService](https://github.com/TrakHound/MTConnect.NET/assets/44919226/25f310fd-3005-4d0c-9412-8bb3414f16cc)

The windows Service name remains the same as MTConnect.Net-Agent. So when I try to install Modbus.exe with admin privileges of cmd the earlier windows service Mitsubishi-MTConnect.Net-Agent gets replaced with Modbus-MTConnect.Net-Agent

![MTCServicename](https://github.com/TrakHound/MTConnect.NET/assets/44919226/2708bb66-729d-4beb-be5c-a2e330c6dce3)
Attached snippet of configuration file

Kindly guide, If I am going wrong

**Comment by PatrickRitchie** [comment]
See if this is fixed in the [v6.4.1 Release](https://github.com/TrakHound/MTConnect.NET/releases/tag/v6.4.1). 

I added serviceDisplayName and serviceDescription in the configuration file:
```yaml
serviceName: Mitsubishi-MTConnect.NET-Agnet
serviceDisplayName: Mitsubishi MTConnect.NET Agent
serviceDescription: MTConnect Agent to read information from a Mitsibishi Machine
```

I also fixed an issue with passing a configuration file path when installing the agent as a service

Please let me know if this is still an issue or if you find anything else.
