### ISSUE TITLE
Module http-adapter not loaded

### ISSUE THREAD

**Issue by anirbanSP** [TrakHound/MTConnect.NET#65]
---

#### Description
Hi,

I have installed the MTConnect agent from the .exe file on my Windows 10 PC. I am trying to launch the .exe with the following configuration:

```yaml
modules:
  - http-adapter:
      address: mtconnect.mazakcorp.com
      port: 5610
      deviceKey: M12346
      interval: 100
      heartbeat: 10000
      useSSL: false
      currentOnly: false
      useStreaming: false
      
  - mqtt-relay:
      server: localhost
      port: 1883
      topicPrefix: MTConnect
      topicStructure: Document
      documentFormat: JSON-CPPAGENT-MQTT
      currentInterval: 5000
      sampleInterval: 5000
      clientId: my-mqtt-client
      reconnectInterval: 10000
      currentOnly: false
```

But the agent logs show that it is not loading the `http-adapter` module for some reason. Here is the log:

```
2024-06-14 12:11:32.5885|INFO|application-logger|Agent Configuration Path = agent.config.yaml
2024-06-14 12:11:32.6718|INFO|application-logger|Configuration File Read Successfully from: C:\Program Files\TrakHound\MTConnect.NET-Agent\agent.config.yaml
2024-06-14 12:11:32.9811|INFO|application-logger|Module Loaded : MQTT Relay
2024-06-14 12:11:35.0843|INFO|modules.mqtt-relay|MQTT Relay Connected to External Broker (localhost:1883)
```

Is there something wrong with the configuration (because it's copied from the example on GitHub)?

#### Steps to Reproduce
1. Install the MTConnect agent using the .exe file on Windows 10.
2. Use the provided configuration.
3. Start the agent and observe the logs.

#### Expected Behavior
The `http-adapter` module should load and connect to the specified address and port.

#### Actual Behavior
The `http-adapter` module does not load, while the `mqtt-relay` module connects successfully.

#### Environment
- Windows 10
- MTConnect.NET Agent version: 6.4.1.0
---
