### ISSUE TITLE
QoS on EntityServer not set correctly

### ISSUE THREAD

**Issue by virizar** [TrakHound/MTConnect.NET#76]
Hi @PatrickRitchie 

We have been testing the mqtt agent v6 on Ubuntu 20 a bit more and we realized that our gateway was missing some data from our publishers

On our agent configuration we have set `qos: 1`  for the `mqtt-relay` module

``` yaml
assetBufferSize: 1000
convertUnits: true
defaultVersion: 2.1
devices: /home/victor/venice_data/state/mt_connect/agent/h350.xml
durable: true
enableMetrics: true
ignoreObservationCase: true
ignoreTimestamps: false
inputValidationLevel: Ignore
modules:
- http-server:
    accept:
      application/json: json
      text/xml: xml
    devicesStyle:
      location: /styles/Devices.xsl
      path: /home/victor/venice_data/state/mt_connect/agent/styles/Devices.xsl
    documentFormat: xml
    files:
    - location: /styles/
      path: /home/victor/venice_data/state/mt_connect/agent/styles
    - location: /schemas/
      path: /home/victor/venice_data/state/mt_connect/agent/schemas
    indentOutput: true
    port: 5000
    responseCompression:
    - gzip
    - br
    streamsStyle:
      location: /styles/Streams.xsl
      path: /home/victor/venice_data/state/mt_connect/agent/styles/Streams.xsl
- shdr-adapter:
    deviceKey: H350
    hostname: localhost
    ignoreHeartbeatOnChange: false
    port: 7878
- mqtt-relay:
    allowUntrustedCertificates: true
    clientId: simulation
    currentInterval: 10000
    documentFormat: JSON
    port: 8883
    qos: 1
    sampleInterval: 500
    server: 192.168.161.204
    tls:
      omitCAValidation: true
      pem:
        certificateAuthority: /home/victor/venice_data/state/mt_connect/gateway_certificates/gateway-SAF-Test-ID/GroupCACertificate.pem
        certificatePath: /home/victor/venice_data/state/mt_connect/gateway_certificates/gateway-SAF-Test-ID/certificate.pem
        privateKeyPath: /home/victor/venice_data/state/mt_connect/gateway_certificates/gateway-SAF-Test-ID/privateKey.pem
      verifyClientCertificate: false
    topicPrefix: MTConnect
    topicStructure: Entity
monitorConfigurationFiles: false
observationBufferSize: 150000
observationIntervals:
- 0
```

However while connecting to our gateway with mqtt-explorer we noticed that the messages were only being received with `QoS = 0`

![qos_bad](https://github.com/user-attachments/assets/c48c4992-4ea0-4ab5-a057-d7eff48b1784)

Going through the code we can see that the mqtt-relay actually ignores the configuration `qos` and sets internally upon initialization QoS 1 as a default 

https://github.com/TrakHound/MTConnect.NET/blob/eb4952c1359e7f6fe95da138f1c6a3cadb9d8a2f/agent/Modules/MTConnect.NET-AgentModule-MqttRelay/Module.cs#L114-L120

We noticed also that the relay sets explicitly the qos on every message when for example a Probe or an Asset request is received, via the use of a `MqttApplicationMessageBuilder`

https://github.com/TrakHound/MTConnect.NET/blob/eb4952c1359e7f6fe95da138f1c6a3cadb9d8a2f/agent/Modules/MTConnect.NET-AgentModule-MqttRelay/Module.cs#L419-L424

The issue comes in the entity server, where the same pattern is used but the explicit setting of the QoS is ommited, which then defaults to 0 when instantiating the `MqttApplicationMessageBuilder`

https://github.com/TrakHound/MTConnect.NET/blob/eb4952c1359e7f6fe95da138f1c6a3cadb9d8a2f/libraries/MTConnect.NET-MQTT/MTConnectMqttEntityServer.cs#L69-L90

There are 4 overrides of the `CreateMessage` method that are not setting the QoS explicitly on the entity server.

adding 

``` csharp
messageBuilder.WithQualityOfServiceLevel(MQTTnet.Protocol.MqttQualityOfServiceLevel.AtLeastOnce);
```

to the message construction steps, correctly sets the QoS to 1 and we can see it reflected in mqtt-explorer

![qos_ok](https://github.com/user-attachments/assets/1e4f172a-28a9-48b4-8268-5d3cd4816cc8)

I have made a PR with this fix
