### ISSUE TITLE
Retain Flag Not Honored by MTConnect Agent

### ISSUE THREAD

**Issue by Pranay265** [TrakHound/MTConnect.NET#85]
Hi @PatrickRitchie 

It appears that the retain flag in MQTT messages is not being honored by the MTConnect agent. When enabled, the retain flag should keep the last known good message for any new subscribers. however, messages from the agent are not retained as expected.

MQTT Relay config:

```
- mqtt-relay: # - Add MQTT Relay module (TLS)
    QoS: 1
    server: localhost
    port: 8883
    clientId: print123
    currentInterval: 10000
    sampleInterval: 500
    allowUntrustedCertificates: true
    documentFormat: JSON
    topicPrefix: MTConnect
    topicStructure: Entity
    tls:
      pem:
        certificateAuthority: certificates/GroupCACertificate.pem
        certificatePath: certificates/certificate.pem
        privateKeyPath: certificates/privateKey.pem
      verifyClientCertificate: false
      omitCAValidation: true

```
**Broker:**
The broker is set up to retain messages, and configuration appears as expected. However, only active data items are visible, not retained ones.

![image (11)](https://github.com/user-attachments/assets/5b0ad479-767a-4ffc-8906-e1c9b97a4e9b)

It’s set as below, but it’s unclear why it’s not getting applied. Am I missing anything in the configuration?

```
private async void ProbeReceived(IDevice device, IDevicesResponseDocument responseDocument)
  {
      if (_mqttClient != null && _mqttClient.IsConnected)
      {
          var x = new List<KeyValuePair<string, string>>();
          x.Add(new KeyValuePair<string, string>("indentOutput", _configuration.IndentOutput.ToString()));

          var formatResult = ResponseDocumentFormatter.Format(_configuration.DocumentFormat, responseDocument, x);
          if (formatResult.Success)
          {
              var topic = $"{_configuration.TopicPrefix}/{MTConnectMqttDocumentServer.ProbeTopic}/{device.Uuid}";
              if (formatResult.Content != null && formatResult.Content.Position > 0) formatResult.Content.Seek(0, SeekOrigin.Begin);

              try
              {
                  var messageBuilder = new MqttApplicationMessageBuilder();
                  messageBuilder.WithRetainFlag(true);
                  messageBuilder.WithTopic(topic);
                  messageBuilder.WithQualityOfServiceLevel(MQTTnet.Protocol.MqttQualityOfServiceLevel.AtLeastOnce);
                  messageBuilder.WithPayload(formatResult.Content);
                  var message = messageBuilder.Build();

```
Please let me know if any additional information needed from my end.
