### ISSUE TITLE
Agent published as Device on mqtt relay 

### ISSUE THREAD

**Issue by virizar** [TrakHound/MTConnect.NET#86]
Hi @PatrickRitchie 

This issue has been noticed on v6.5 using Ubuntu

Here is the configuration of our `mqtt-relay`

``` yaml
- mqtt-relay:
    allowUntrustedCertificates: true
    clientId: simulation
    currentInterval: 10000
    documentFormat: JSON
    port: 8883
    qos: 1
    sampleInterval: 500
    server: 192.168.161.164
    tls:
      omitCAValidation: true
      pem:
        certificateAuthority: GroupCACertificate.pem
        certificatePath:certificate.pem
        privateKeyPath: privateKey.pem
      verifyClientCertificate: false
    topicPrefix: MTConnect
    topicStructure: Entity
```

We are noticing on our brokers that, when the agent connects, it is adding itself as a Device on the data stream of the mqtt relay. Below is a screenshot of us monitoring one of our brokers when an agent is connected. We see that the GUID of the agent is added to the `MTConnect/Devices` prefix

![image](https://github.com/user-attachments/assets/c4b680be-a1bb-4aef-893d-bc51e10150f2)

We were expecting the agent to publish on `MTConnect/Agents` prefix since we know that this is the way the v5 agent is handling this. 

Also the README's regarding this on the master branch also suggest that the agents are expected to be publishing on the `MTConnect/Agents` prefix 

https://github.com/TrakHound/MTConnect.NET/blob/cb12bbd2f3a518d4f7b9fc49c8e8a9c4a83c1a6c/docs/MQTT-Protocol.md?plain=1#L57-L95

I have been inspecting the code and I can see that the entity server `CreateMessage` method always refers to the topic `<PREFIX>/Devices/*` when creating messages for observations

https://github.com/TrakHound/MTConnect.NET/blob/cb12bbd2f3a518d4f7b9fc49c8e8a9c4a83c1a6c/libraries/MTConnect.NET-MQTT/MTConnectMqttEntityServer.cs#L150-L211
 
There is a `CreateMessage` overload that takes a Device as an argument and it would make sense that the message is created for a device

I failed to understand where the agent is being added as a device in the code, but I imagine there is a need to have `CreateMessage` for agents and use that for the messages that the agent is publishing? maybe is there a way that, via configuration, we can avoid including the agent as part of the data stream?
